# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u2INMCu0KN6UcFvTMOQ32WSzGWoKpBhL
"""

import pandas as pd #type:ignore
import pickle
import numpy as np
from sklearn.linear_model import LinearRegression #type:ignore
from sklearn.model_selection import train_test_split #type:ignore
from sklearn import linear_model #type:ignore

df = pd.read_excel("DataCar.xlsx")
df.head()

df

df.info()

df['Cylinders'].unique()

df['Origin'].unique()

df['Cylinders_int'] = df['Cylinders'].map({'8' : 1, '4' : 2, '6' : 3, '3' : 4, '5': 5})
df['Origin_int'] = df['Origin'].map({'US' : 1, 'Europe' : 2, 'Japan' : 3})

X = df[['MPG',	'Cylinders',	'Horsepower', 'Weight','Acceleration',	'Model']]
y = df['Displacement']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 101)

model = linear_model.LinearRegression()

model.fit(X_train, y_train)
print(model.score(X_train, y_train))

prediction_test = model.predict(X_test)
print(y_test, prediction_test)
print("Predict = ", np.mean(prediction_test-y_test)**2)

pickle.dump(model, open('model.pkl', 'wb'))

model = pickle.load(open('model.pkl', 'rb'))